# Analizes Pagrindai

<hr>

# NumPy

Numpy - tai pythono biblioteka, skirta tiesines algebros skaiciavimams

In [14]:
import numpy as np

In [15]:
listas = [1,2,3,4,5]

`List` - python

`Array` - numpy

In [18]:
arr = np.array(listas)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [21]:
arr.shape

(5,)

Tuščias numpy array

In [20]:
np.array([])

array([], dtype=float64)

In [27]:
mano_listai = [[1,2,3],[4,5,6],[7,8,9]]
matrica = np.array(mano_listai)

In [28]:
matrica

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<hr>

Ar matrica turi butinai buti kvadratine (tiek pat eiluciu, kiek ir stulpeliu)? 

Ats: Ne

In [30]:
mano_listai_1 = [[1,2,3],[4,5,6]]
matrica_1 = np.array(mano_listai_1)

In [31]:
matrica_1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
matrica_1.shape

(2, 3)

<hr>

[0 : 30) kas 3

In [33]:
arr1 = np.arange(0, 30, 3)

In [34]:
arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Jei norime nuliu vektoriaus

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

0 -> 20, 16 reiksmiu

In [64]:
np.linspace(0, 100, 101)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [57]:
tarpas = (20 - 0) / (16 - 1)
x = 0
list1 = []
while x < 20:
    list1.append(x)
    x += tarpas

In [80]:
np.eye(60)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

<hr>

Klausimas:
    
- Kaip paversti numpy array i python list?

Atsakymas:
    

In [70]:
list(np.array([1,2,3]))

[1, 2, 3]

In [71]:
np.array([1,2,3]).tolist()

[1, 2, 3]

## Random Arrays

Random -> uniform

In [82]:
np.random.rand(3)

array([0.86626859, 0.43124267, 0.91447452])

Nuotrauka -> pikseliai 

pikselis => ([[R,G,B], [Intensity]]) 

In [103]:
np.random.rand(3,3)

array([[0.82746131, 0.60736084, 0.94175843],
       [0.52184475, 0.87693779, 0.08581603],
       [0.90383307, 0.94582554, 0.1108376 ]])

In [86]:
np.random.randn(100,100)

array([[ 0.08005063,  0.58498201,  2.55397077, ..., -1.15130325,
        -1.40892425,  0.59391592],
       [-1.37770807, -0.55925025, -0.43761284, ..., -0.81162158,
         0.37423515,  0.14110842],
       [-1.15137973, -0.1426408 ,  2.04814445, ...,  0.35225606,
        -0.77130177, -1.01633596],
       ...,
       [ 1.4214243 , -1.41813302, -0.27471545, ..., -0.87853772,
         0.80314453, -1.68620543],
       [ 0.3690061 , -1.19847571, -1.41903494, ..., -0.79015617,
        -0.11336021,  0.06157817],
       [ 0.63532607, -1.67807569, -1.97017335, ...,  0.55656299,
         0.67380911, -1.71842445]])

Gaussian (standard normal distribution)

In [87]:
np.random.randint(100, 200, 20)

array([166, 138, 199, 190, 192, 142, 127, 135, 136, 114, 162, 106, 129,
       187, 148, 147, 127, 162, 131, 103])

## Masyvu Pertvarkymas

In [110]:
my_array = np.random.randint(0, 100, 64)

In [111]:
my_array

array([37, 84, 25, 97, 36, 60, 97, 71, 91, 92, 22, 99, 42, 82, 14, 30, 81,
       47, 83, 35,  1, 23, 87, 21,  6,  3, 48, 14,  5, 48, 30, 88, 87, 58,
       81, 18, 97, 55, 93, 61, 79, 88, 61, 68, 11, 95, 96, 90, 94, 48, 71,
       37, 59, 85,  6, 69, 51, 85, 23, 27, 94, 11, 33,  4])

In [112]:
my_array.shape

(64,)

In [113]:
reshaped_array = my_array.reshape(8,8)

In [116]:
reshaped_array

array([[37, 84, 25, 97, 36, 60, 97, 71],
       [91, 92, 22, 99, 42, 82, 14, 30],
       [81, 47, 83, 35,  1, 23, 87, 21],
       [ 6,  3, 48, 14,  5, 48, 30, 88],
       [87, 58, 81, 18, 97, 55, 93, 61],
       [79, 88, 61, 68, 11, 95, 96, 90],
       [94, 48, 71, 37, 59, 85,  6, 69],
       [51, 85, 23, 27, 94, 11, 33,  4]])

## Naudingi Metodai

In [119]:
my_array

array([37, 84, 25, 97, 36, 60, 97, 71, 91, 92, 22, 99, 42, 82, 14, 30, 81,
       47, 83, 35,  1, 23, 87, 21,  6,  3, 48, 14,  5, 48, 30, 88, 87, 58,
       81, 18, 97, 55, 93, 61, 79, 88, 61, 68, 11, 95, 96, 90, 94, 48, 71,
       37, 59, 85,  6, 69, 51, 85, 23, 27, 94, 11, 33,  4])

In [124]:
my_array.min()

1

In [125]:
my_array.max()

99

In [129]:
my_array.argmax()

11

In [130]:
my_array.argmin()

20

In [131]:
my_array.dtype

dtype('int64')

In [133]:
my_array = my_array.astype('int8')

array([37, 84, 25, 97, 36, 60, 97, 71, 91, 92, 22, 99, 42, 82, 14, 30, 81,
       47, 83, 35,  1, 23, 87, 21,  6,  3, 48, 14,  5, 48, 30, 88, 87, 58,
       81, 18, 97, 55, 93, 61, 79, 88, 61, 68, 11, 95, 96, 90, 94, 48, 71,
       37, 59, 85,  6, 69, 51, 85, 23, 27, 94, 11, 33,  4], dtype=int8)

## Indeksacija ir reiksmiu priskyrimas

In [134]:
sample_arr = np.arange(1,10)

In [135]:
sample_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
sample_arr[5]

6

slices:

In [140]:
sample_arr[2:8]

array([3, 4, 5, 6, 7, 8])

In [143]:
sample_arr[5:]

array([6, 7, 8, 9])

In [144]:
sample_arr[-5:]

array([5, 6, 7, 8, 9])

Priskyrimas (Broadcasting)

In [146]:
sample_arr[3:7] = 30

In [147]:
sample_arr

array([ 1,  2,  3, 30, 30, 30, 30,  8,  9])

## Reiksmiu traukimas is matricos

In [148]:
samp = np.random.randint(1,10,25)

In [150]:
sample_matrix = samp.reshape(5,5)

In [151]:
sample_matrix


array([[1, 2, 6, 8, 7],
       [1, 3, 3, 9, 8],
       [8, 2, 3, 7, 4],
       [9, 9, 3, 7, 6],
       [9, 5, 6, 1, 9]])

In [162]:
sample_matrix[1, 2]

6

In [163]:
sample_matrix[1:4, 1:4]

array([[3, 3, 9],
       [2, 3, 7],
       [9, 3, 7]])

In [169]:
sample_matrix[:, :]

array([[1, 2, 6, 8, 7],
       [1, 3, 3, 9, 8],
       [8, 2, 3, 7, 4],
       [9, 9, 3, 7, 6],
       [9, 5, 6, 1, 9]])

In [174]:
sample_matrix.reshape(5,5,1).shape

(5, 5, 1)

In [176]:
sample_matrix

array([[1, 2, 6, 8, 7],
       [1, 3, 3, 9, 8],
       [8, 2, 3, 7, 4],
       [9, 9, 3, 7, 6],
       [9, 5, 6, 1, 9]])

In [177]:
vect_ = np.array([1,2,4,5])

In [180]:
vect_

array([1, 2, 4, 5])

Ka reiskia keli dvitaskiai pasirenkant elementus matricoje/vektoriuje?

`vektorius[pradzia:pabaiga:zingsnelis]`

In [182]:
vect_[1::2]

array([2, 5])

## Reiksmiu traukimas pagal salyga

In [183]:
masyvas = np.arange(1,21)

In [184]:
masyvas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [186]:
boolean_masyvas = masyvas > 7

In [187]:
boolean_masyvas

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [188]:
masyvas[boolean_masyvas]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [189]:
masyvas[masyvas > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Numpy elgsenos ypatumai

In [190]:
arr5 = np.random.randint(1, 21, 20)

In [191]:
arr5

array([11,  6,  7, 14, 17,  9, 12,  9, 16, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

In [192]:
slice_ = arr5[1:9]

In [193]:
slice_

array([ 6,  7, 14, 17,  9, 12,  9, 16])

In [195]:
slice_[:] = 78

In [198]:
arr5

array([11, 78, 78, 78, 78, 78, 78, 78, 78, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

In [199]:
arr5_copy = arr5.copy()


In [200]:
arr5_copy

array([11, 78, 78, 78, 78, 78, 78, 78, 78, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

#### !DANGER!

In [201]:
arr6 = arr5

In [202]:
arr6

array([11, 78, 78, 78, 78, 78, 78, 78, 78, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

In [203]:
arr5

array([11, 78, 78, 78, 78, 78, 78, 78, 78, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

In [204]:
arr6[:] = 100

In [205]:
arr5

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [206]:
arr6

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [207]:
arr5_copy

array([11, 78, 78, 78, 78, 78, 78, 78, 78, 14,  7,  9, 20,  3, 10, 19, 10,
        4, 18, 17])

##  Matematika

In [208]:
vect = np.arange(1,11)

In [209]:
vect

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [210]:
vect * vect

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

$$ x * x = [x_{1} * x_{1}, x_{2}*x_{2} ...] $$

In [211]:
vect + vect

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [212]:
vect + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [214]:
vect / vect

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [215]:
vect / 0

/var/folders/9h/pxgsfw7n1h1bdydh77wmr1q40000gn/T/ipykernel_10360/994288185.py:1: RuntimeWarning:

divide by zero encountered in divide



array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [218]:
np.inf > 1000

True